; php.ini minimal g n r  par launch_server.py
display_errors = On
error_reporting = E_ALL
date.timezone = Europe/Paris

extension_dir = "ext"
extension=pdo_mysql
extension=mysqli
extension=fileinfo
opcache.enable=0
opcache.enable_cli=0
